# Alertmanager Configuration for ORFEAS Enterprise Agent System
global:
  # SMTP configuration for email alerts
  smtp_smarthost: "localhost:587"
  smtp_from: "alerts@orfeas.ai"
  smtp_auth_username: "alerts@orfeas.ai"
  smtp_auth_password: "your_smtp_password"

  # Default Slack configuration
  slack_api_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"

# Templates for alert messages
templates:
  - "/etc/alertmanager/templates/*.tmpl"

# Route configuration
route:
  group_by: ["alertname", "cluster", "service"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "default-receiver"

  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: "critical-alerts"
      group_wait: 0s
      repeat_interval: 15m

    # Warning alerts - less frequent notifications
    - match:
        severity: warning
      receiver: "warning-alerts"
      repeat_interval: 2h

    # Agent-specific alerts
    - match:
        service: orfeas-agents
      receiver: "agent-alerts"

    # GPU-specific alerts
    - match:
        service: orfeas-gpu
      receiver: "gpu-alerts"

    # System resource alerts
    - match:
        service: system
      receiver: "system-alerts"

# Receivers configuration
receivers:
  - name: "default-receiver"
    email_configs:
      - to: "ops@orfeas.ai"
        subject: "ORFEAS Alert: {{ .GroupLabels.alertname }}"
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Time: {{ .StartsAt }}
          {{ end }}

  - name: "critical-alerts"
    email_configs:
      - to: "critical@orfeas.ai"
        subject: " CRITICAL ALERT: {{ .GroupLabels.alertname }}"
        body: |
           CRITICAL ALERT 

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Time: {{ .StartsAt }}

          Immediate action required!
          {{ end }}

    slack_configs:
      - api_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        channel: "#critical-alerts"
        title: " CRITICAL ALERT: {{ .GroupLabels.alertname }}"
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Time:* {{ .StartsAt }}
          {{ end }}
        send_resolved: true

  - name: "warning-alerts"
    email_configs:
      - to: "warnings@orfeas.ai"
        subject: " WARNING: {{ .GroupLabels.alertname }}"
        body: |
           WARNING ALERT 

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Time: {{ .StartsAt }}
          {{ end }}

    slack_configs:
      - api_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        channel: "#warning-alerts"
        title: " WARNING: {{ .GroupLabels.alertname }}"
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Time:* {{ .StartsAt }}
          {{ end }}
        send_resolved: true

  - name: "agent-alerts"
    email_configs:
      - to: "agents@orfeas.ai"
        subject: " AGENT ALERT: {{ .GroupLabels.alertname }}"
        body: |
           ENTERPRISE AGENT SYSTEM ALERT 

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Time: {{ .StartsAt }}

          Agent system requires attention.
          {{ end }}

    slack_configs:
      - api_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        channel: "#agent-monitoring"
        title: " AGENT ALERT: {{ .GroupLabels.alertname }}"
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Time:* {{ .StartsAt }}
          {{ end }}
        send_resolved: true

  - name: "gpu-alerts"
    email_configs:
      - to: "gpu@orfeas.ai"
        subject: " GPU ALERT: {{ .GroupLabels.alertname }}"
        body: |
           GPU SYSTEM ALERT 

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Time: {{ .StartsAt }}

          GPU system requires immediate attention.
          {{ end }}

    slack_configs:
      - api_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        channel: "#gpu-monitoring"
        title: " GPU ALERT: {{ .GroupLabels.alertname }}"
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Time:* {{ .StartsAt }}
          {{ end }}
        send_resolved: true

  - name: "system-alerts"
    email_configs:
      - to: "system@orfeas.ai"
        subject: " SYSTEM ALERT: {{ .GroupLabels.alertname }}"
        body: |
           SYSTEM RESOURCE ALERT 

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Time: {{ .StartsAt }}
          {{ end }}

    slack_configs:
      - api_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        channel: "#system-monitoring"
        title: " SYSTEM ALERT: {{ .GroupLabels.alertname }}"
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Time:* {{ .StartsAt }}
          {{ end }}
        send_resolved: true

# Inhibit rules to prevent alert spam
inhibit_rules:
  # Inhibit warning alerts when critical alerts are firing
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "service", "instance"]

  # Inhibit container alerts when the whole system is down
  - source_match:
      alertname: "OrfeasBackendDown"
    target_match_re:
      alertname: ".*Container.*"
    equal: ["instance"]

  # Inhibit individual agent alerts when agent system is down
  - source_match:
      alertname: "OrfeasAgentSystemDown"
    target_match_re:
      alertname: "OrfeasAgent.*"
    equal: ["instance"]
