# HYBRID DEPLOYMENT: LOCAL BACKEND + DOCKER MONITORING
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'orfeas-local-production'
    environment: 'hybrid'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'orfeas-backend-local'
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['nvidia-gpu-exporter:9445']
    scrape_interval: 10s
