global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'orfeas-monitor'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Scrape configurations
scrape_configs:
  - job_name: 'orfeas_backend'
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 9s
